### ISSUE TITLE
Backbone: autoBundle issues

### ISSUE THREAD

**Issue by Iamcerba** [vtfuture/RequireJSDotNet#58]
Hello,

I'm experiencing issues when using Backbone.js (v. 1.2.1) (http://backbonejs.org/) as part of autoBundle.

I believe that this occurs due to Backbone.js uses the following dependencies:

``` javascript
25 line:   var _ = require('underscore'), $;
26 line:   try { $ = require('jquery'); } catch(e) {}
```

Simple change solves the problem, but it requires modification third party lib:

``` javascript
25 line:   var _ = require(['underscore']), $;
26 line:   try { $ = require(['jquery']); } catch(e) {}
```

Simple config example:

``` javascript
{
    "paths": {
        "jquery": "libs/jquery-2.1.3",
        "underscore": "libs/underscore",
        "backbone": "libs/backbone"
    },
    "autoBundles": {
        "app": {
            "outputPath": "Content\\js\\bundles\\",
            "include": [
                {
                    "file": "libs\\backbone"
                }
            ]
        }
    }
}
```

Error during compilation:

``` javascript
Error   14  Exception: Error while processing libs\backbone.js: Could not read argument for require() call libs\backbone.js
   at RequireJsNet.Compressor.AutoDependency.ScriptProcessor.Process() in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\ScriptProcessor.cs:line 92
   at RequireJsNet.Compressor.RequireProcessing.AutoBundleConfigProcessor.ParseConfigs() in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\RequireProcessing\AutoBundleConfigProcessor.cs:line 100
   at RequireJsNet.Compressor.RequireCompressorTask.Execute() in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\Tasks\RequireCompressorTask.cs:line 67
Exception: Could not read argument for require() call libs\backbone.js
   at RequireJsNet.Compressor.Parsing.RequireVisitor.ProcessRequireCall(RequireCall& parentCall, CallExpression callExpression, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 336
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitExpression(Expression node, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 210
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitExpression(Expression node, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 262
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitNodeEnumerator(IEnumerable`1 nodes, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 158
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitStatement(Statement statement, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 112
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitNodeEnumerator(IEnumerable`1 nodes, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 154
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitStatement(Statement statement, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 71
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitStatement(Statement statement, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 96
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitStatement(Statement statement, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 95
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitNodeEnumerator(IEnumerable`1 nodes, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 154
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitStatement(Statement statement, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 71
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitExpression(Expression node, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 232
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitExpression(Expression node, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 220
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitStatement(Statement statement, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 79
   at RequireJsNet.Compressor.Parsing.RequireVisitor.VisitNodeEnumerator(IEnumerable`1 nodes, RequireCall parentCall, NodeWithChildren parentNode) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 154
   at RequireJsNet.Compressor.Parsing.RequireVisitor.Visit(Program program, String relativeFileName) in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\Parsing\RequireVisitor.cs:line 45
   at RequireJsNet.Compressor.AutoDependency.ScriptProcessor.Process() in d:\Download\RequireJSDotNet-master (1)\RequireJSDotNet-master\RequireJsNet.Compressor\AutoDependency\ScriptProcessor.cs:line 50
```

Maybe problem within RequireVisitor.cs?

``` javascript
private void ProcessRequireCall(ref RequireCall parentCall, CallExpression callExpression, NodeWithChildren parentNode)
        {
            var argCount = callExpression.Arguments.Count();
            if (argCount < 1 || argCount > 2)
            {
                throw new Exception("Invalid number of arguments for require() call " + relativeFileName);
            }

            var requireCall = new RequireCall
                                  {
                                      Type = RequireCallType.Require,
                                      ParentNode = parentNode
                                  };

            if (parentCall != null)
            {
                parentCall.Children.Add(requireCall);
            }
            else
            {
                result.RequireCalls.Add(requireCall);
            }

            parentCall = requireCall;

            var firstArg = callExpression.Arguments.First();
            var secondArg = callExpression.Arguments.Last();

            if (argCount == 1)
            {
                if (firstArg is Literal)
                {
                    var singleDep = firstArg.As<Literal>();
                    requireCall.SingleDependencyNode = singleDep;
                    requireCall.Dependencies.Add(singleDep.Value.ToString());
                }
                if (firstArg is ArrayExpression)   // <-- "else if" makes sense in this place?
                {
                    var deps = this.ProcessDependencyArray(firstArg, requireCall);
                    requireCall.Dependencies.AddRange(deps);
                }
                else
                {
                    throw new Exception("Could not read argument for require() call " + relativeFileName);
                }
            }
            else if (argCount == 2)
            {
                requireCall.IsModule = true;
                var deps = this.ProcessDependencyArray(firstArg, requireCall);
                requireCall.Dependencies.AddRange(deps);

                this.ProcessModuleDefinition(secondArg, parentCall, parentNode);
            }
        }
```

**Comment by aquamoth** [comment]
This issue is fixed in latest master branch
