### ISSUE TITLE
building RequireJsNet.Compressor.Demo fails

### ISSUE THREAD

**Issue by gregveres** [vtfuture/RequireJSDotNet#80]
HI

I just cloned the Git repo to my desktop, opened the solution and built it. The RequireJsNet.Compressor.Demo fails to build. There is a null reference crash during the build. I assume it is during the bundling but I can't even begin to figure out where to look. The reason I was building the demo was try to figure out the bundling feature which is eluding me right now. 

Can somebody take a look at why the demo is failing to build? Does it build properly for others? 

Thanks
Greg

```
6>------ Build started: Project: RequireJsNet.Compressor.Demo, Configuration: Debug Any CPU ------
6>  Restoring NuGet packages...
6>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
6>  Feeds used:
6>    C:\Users\gregv\AppData\Local\NuGet\Cache
6>    C:\Users\gregv\.nuget\packages\
6>    https://api.nuget.org/v3/index.json
6>    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
6>  
6>  All packages listed in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\packages.config are already installed.
6>  RequireJsNet.Compressor.Demo -> C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\bin\RequireJsNet.Compressor.Demo.dll
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error : NullReferenceException: Attribute compressionType is null.
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Helpers.XmlReaderHelpers.ReadStringAttribute(XElement element, String attributeName, AttributeReadType readType) in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet\Helpers\XmlReaderHelpers.cs:line 41
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Configuration.XmlReader.AutoBundleReader(XElement element) in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet\Configuration\XmlReader.cs:line 212
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Configuration.XmlReader.GetAutoBundles(XElement root) in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet\Configuration\XmlReader.cs:line 131
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Configuration.XmlReader.ReadConfig() in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet\Configuration\XmlReader.cs:line 54
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Configuration.ConfigLoader.Get() in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet\Configuration\ConfigLoader.cs:line 40
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Compressor.RequireProcessing.AutoBundleConfigProcessor.ParseConfigs() in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor\RequireProcessing\AutoBundleConfigProcessor.cs:line 56
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error :    at RequireJsNet.Compressor.RequireCompressorTask.Execute() in C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor\Tasks\RequireCompressorTask.cs:line 67
6>C:\Users\gregv\Documents\GitHub\RequireJSDotNet\RequireJsNet.Compressor.Demo\BuildTools\MinifyBundlesTaskSubfolder.proj(4,5): error : 

```

**Comment by aquamoth** [comment]
My bad. This is fixed in master now.
